name: TMDB Pipeline Infra and Applications

on:
  push:
    branches: [main]
  workflow_dispatch: 


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${ { secrets.AWS_ACCESS_KEY_ID } }
        aws-secret-access-key: ${ { secrets.AWS_SECRET_ACCESS_KEY } }
        aws-region: "us-east-1"

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: ./terraform
      env:
        TF_VAR_tmdb_api_key: $ { { secrets.API_KEY } }
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./terraform
      env:
        TF_VAR_tmdb_api_key: $ { { secrets.API_KEY } }
      run: terraform apply -auto-approve

