name: TMDB CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install Dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: | 
        python -m pytest

    - name: Login To ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Build and Push Docker image
      run: |
        docker buildx build \
          --platform linux/arm64 \
          --tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/tmdb-images:latest \
          --output=type=registry,oci-mediatypes=false \
          .


      
    - name: Update Lambda Functions
      run: |
        export AWS_PAGER=""
        for lambda_func in "movies_ingestion" "movie_details_ingestion" "movie_reviews_ingestion" "movie_providers_ingestion" "movie_credits_ingestion"
        do 
            aws lambda update-function-code \
                    --function-name $lambda_func \
                    --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/tmdb-images:latest
        done

